language: workflow

tools:
  jdk:
    - 1.8.0_91-b14
  maven:
    - 3.3.9

flows:
  master:
  - (on master, name mvn clean deploy -Ppublish-site) mvn clean deploy -Ppublish-site -B 
  pr:
  - call: master
